// @generated by zf crud:zent — AI: edit actions table; then `zf routes`
const handler = @import("handler.zig");

pub const module = .{
    .name = "shop",
    .prefix = "/api/v1",
};

pub const actions = .{
    .{ .name = "createUser", .method = .POST, .action_key = "/api/v1/users", .handler = handler.createUser },
    .{ .name = "updateUser", .method = .PUT, .action_key = "/api/v1/users", .handler = handler.updateUser },
    .{ .name = "deleteUser", .method = .DELETE, .action_key = "/api/v1/users", .handler = handler.deleteUser },
    .{ .name = "createProduct", .method = .POST, .action_key = "/api/v1/products", .handler = handler.createProduct },
    .{ .name = "updateProduct", .method = .PUT, .action_key = "/api/v1/products", .handler = handler.updateProduct },
    .{ .name = "deleteProduct", .method = .DELETE, .action_key = "/api/v1/products", .handler = handler.deleteProduct },
    .{ .name = "listProduct", .method = .GET, .action_key = "/api/v1/products", .handler = handler.listProduct },
    .{ .name = "createCartItem", .method = .POST, .action_key = "/api/v1/cart_items", .handler = handler.createCartItem },
    .{ .name = "updateCartItem", .method = .PUT, .action_key = "/api/v1/cart_items", .handler = handler.updateCartItem },
    .{ .name = "deleteCartItem", .method = .DELETE, .action_key = "/api/v1/cart_items", .handler = handler.deleteCartItem },
    .{ .name = "listCartItem", .method = .GET, .action_key = "/api/v1/cart_items", .handler = handler.listCartItem },
    .{ .name = "createOrder", .method = .POST, .action_key = "/api/v1/orders", .handler = handler.createOrder },
    .{ .name = "updateOrder", .method = .PUT, .action_key = "/api/v1/orders", .handler = handler.updateOrder },
    .{ .name = "deleteOrder", .method = .DELETE, .action_key = "/api/v1/orders", .handler = handler.deleteOrder },
    .{ .name = "createOrderItem", .method = .POST, .action_key = "/api/v1/order_items", .handler = handler.createOrderItem },
    .{ .name = "updateOrderItem", .method = .PUT, .action_key = "/api/v1/order_items", .handler = handler.updateOrderItem },
    .{ .name = "deleteOrderItem", .method = .DELETE, .action_key = "/api/v1/order_items", .handler = handler.deleteOrderItem },
    .{ .name = "listOrderItem", .method = .GET, .action_key = "/api/v1/order_items", .handler = handler.listOrderItem },
    .{ .name = "createFollow", .method = .POST, .action_key = "/api/v1/follows", .handler = handler.createFollow },
    .{ .name = "updateFollow", .method = .PUT, .action_key = "/api/v1/follows", .handler = handler.updateFollow },
    .{ .name = "deleteFollow", .method = .DELETE, .action_key = "/api/v1/follows", .handler = handler.deleteFollow },
    .{ .name = "listFollow", .method = .GET, .action_key = "/api/v1/follows", .handler = handler.listFollow },
    .{ .name = "createLike", .method = .POST, .action_key = "/api/v1/likes", .handler = handler.createLike },
    .{ .name = "updateLike", .method = .PUT, .action_key = "/api/v1/likes", .handler = handler.updateLike },
    .{ .name = "deleteLike", .method = .DELETE, .action_key = "/api/v1/likes", .handler = handler.deleteLike },
    .{ .name = "listLike", .method = .GET, .action_key = "/api/v1/likes", .handler = handler.listLike },
    .{ .name = "createPost", .method = .POST, .action_key = "/api/v1/posts", .handler = handler.createPost },
    .{ .name = "updatePost", .method = .PUT, .action_key = "/api/v1/posts", .handler = handler.updatePost },
    .{ .name = "deletePost", .method = .DELETE, .action_key = "/api/v1/posts", .handler = handler.deletePost },
    .{ .name = "listPost", .method = .GET, .action_key = "/api/v1/posts", .handler = handler.listPost },
    .{ .name = "createComment", .method = .POST, .action_key = "/api/v1/comments", .handler = handler.createComment },
    .{ .name = "updateComment", .method = .PUT, .action_key = "/api/v1/comments", .handler = handler.updateComment },
    .{ .name = "deleteComment", .method = .DELETE, .action_key = "/api/v1/comments", .handler = handler.deleteComment },
    .{ .name = "listComment", .method = .GET, .action_key = "/api/v1/comments", .handler = handler.listComment },
    // ── ai-edit-zone: extra actions ───────────────────────────────
    .{ .name = "checkout", .method = .POST, .action_key = "/api/v1/orders/checkout", .handler = handler.checkout },
    .{ .name = "feed", .method = .GET, .action_key = "/api/v1/feed", .handler = handler.feed },
    .{ .name = "recommend", .method = .GET, .action_key = "/api/v1/recommend", .handler = handler.recommend },
    .{ .name = "login", .method = .POST, .action_key = "/api/v1/auth/login", .handler = handler.login },
    .{ .name = "listMyOrders", .method = .GET, .action_key = "/api/v1/orders/mine", .handler = handler.listMyOrders },
    // ── end ai-edit-zone ──────────────────────────────────────────
};
