// @generated by `zf crud:zent` — AI: edit inside ai-edit-zone only.
const std = @import("std");
const zfinal = @import("zfinal");
const service = @import("service.zig");

pub var g_svc: ?*service.ShopService = null;

fn svcOrErr(ctx: *zfinal.Context) !*service.ShopService {
    _ = ctx;
    return g_svc orelse error.ServiceNotReady;
}

pub fn createUser(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    // ── ai-edit-zone: handler hooks ───────────────────────────────
    const name = try ctx.getPara("name") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing name" });
        return;
    };
    const handle = try ctx.getPara("handle") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing handle" });
        return;
    };
    const email = try ctx.getPara("email") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing email" });
        return;
    };
    // ── end ai-edit-zone ──────────────────────────────────────────
    const id = svc.createUser(name, handle, email) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true, .id = id });
}

pub fn updateUser(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    const name = try ctx.getPara("name") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing name" });
        return;
    };
    const handle = try ctx.getPara("handle") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing handle" });
        return;
    };
    const email = try ctx.getPara("email") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing email" });
        return;
    };
    svc.updateUser(id, name, handle, email) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn deleteUser(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    svc.deleteUser(id) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn createProduct(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    // ── ai-edit-zone: handler hooks ───────────────────────────────
    const seller_id = try ctx.getParaToLong("seller_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing seller_id" });
        return;
    };
    const name = try ctx.getPara("name") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing name" });
        return;
    };
    const price_cents = try ctx.getParaToLong("price_cents") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing price_cents" });
        return;
    };
    const stock = try ctx.getParaToLongDefault("stock", 0);
    // ── end ai-edit-zone ──────────────────────────────────────────
    const id = svc.createProduct(seller_id, name, price_cents, stock) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true, .id = id });
}

pub fn updateProduct(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    const seller_id = try ctx.getParaToLong("seller_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing seller_id" });
        return;
    };
    const name = try ctx.getPara("name") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing name" });
        return;
    };
    const price_cents = try ctx.getParaToLong("price_cents") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing price_cents" });
        return;
    };
    const stock = try ctx.getParaToLongDefault("stock", 0);
    svc.updateProduct(id, seller_id, name, price_cents, stock) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn deleteProduct(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    svc.deleteProduct(id) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn listProduct(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const seller_id = try ctx.getParaToLong("seller_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing seller_id" });
        return;
    };
    const page: usize = @intCast(try ctx.getParaToLongDefault("page", 1));
    const size: usize = @intCast(try ctx.getParaToLongDefault("size", 0)); // 0 = all
    const pageresult = svc.listProduct(seller_id, page, size) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    defer svc.freeProducts(pageresult.rows);
    try ctx.renderJson(.{ .ok = true, .products = pageresult.rows, .meta = .{ .total = pageresult.total, .page = page, .size = size } });
}

pub fn createCartItem(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    // ── ai-edit-zone: handler hooks ───────────────────────────────
    const user_id = try ctx.getParaToLong("user_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing user_id" });
        return;
    };
    const product_id = try ctx.getParaToLong("product_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing product_id" });
        return;
    };
    const qty = try ctx.getParaToLongDefault("qty", 1);
    // ── end ai-edit-zone ──────────────────────────────────────────
    const id = svc.createCartItem(user_id, product_id, qty) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true, .id = id });
}

pub fn updateCartItem(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    const user_id = try ctx.getParaToLong("user_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing user_id" });
        return;
    };
    const product_id = try ctx.getParaToLong("product_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing product_id" });
        return;
    };
    const qty = try ctx.getParaToLongDefault("qty", 1);
    svc.updateCartItem(id, user_id, product_id, qty) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn deleteCartItem(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    svc.deleteCartItem(id) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn listCartItem(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const user_id = try ctx.getParaToLong("user_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing user_id" });
        return;
    };
    const page: usize = @intCast(try ctx.getParaToLongDefault("page", 1));
    const size: usize = @intCast(try ctx.getParaToLongDefault("size", 0)); // 0 = all
    const pageresult = svc.listCartItem(user_id, page, size) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    defer svc.freeCartItems(pageresult.rows);
    try ctx.renderJson(.{ .ok = true, .cart_items = pageresult.rows, .meta = .{ .total = pageresult.total, .page = page, .size = size } });
}

pub fn createOrder(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    // ── ai-edit-zone: handler hooks ───────────────────────────────
    const buyer_id = try ctx.getParaToLong("buyer_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing buyer_id" });
        return;
    };
    const status = try ctx.getPara("status") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing status" });
        return;
    };
    const total_cents = try ctx.getParaToLongDefault("total_cents", 0);
    // ── end ai-edit-zone ──────────────────────────────────────────
    const id = svc.createOrder(buyer_id, status, total_cents) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true, .id = id });
}

pub fn updateOrder(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    const buyer_id = try ctx.getParaToLong("buyer_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing buyer_id" });
        return;
    };
    const status = try ctx.getPara("status") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing status" });
        return;
    };
    const total_cents = try ctx.getParaToLongDefault("total_cents", 0);
    svc.updateOrder(id, buyer_id, status, total_cents) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn deleteOrder(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    svc.deleteOrder(id) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn createOrderItem(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    // ── ai-edit-zone: handler hooks ───────────────────────────────
    const order_id = try ctx.getParaToLong("order_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing order_id" });
        return;
    };
    const product_id = try ctx.getParaToLong("product_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing product_id" });
        return;
    };
    const qty = try ctx.getParaToLong("qty") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing qty" });
        return;
    };
    const price_cents = try ctx.getParaToLong("price_cents") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing price_cents" });
        return;
    };
    // ── end ai-edit-zone ──────────────────────────────────────────
    const id = svc.createOrderItem(order_id, product_id, qty, price_cents) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true, .id = id });
}

pub fn updateOrderItem(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    const order_id = try ctx.getParaToLong("order_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing order_id" });
        return;
    };
    const product_id = try ctx.getParaToLong("product_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing product_id" });
        return;
    };
    const qty = try ctx.getParaToLong("qty") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing qty" });
        return;
    };
    const price_cents = try ctx.getParaToLong("price_cents") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing price_cents" });
        return;
    };
    svc.updateOrderItem(id, order_id, product_id, qty, price_cents) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn deleteOrderItem(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    svc.deleteOrderItem(id) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn listOrderItem(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const order_id = try ctx.getParaToLong("order_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing order_id" });
        return;
    };
    const page: usize = @intCast(try ctx.getParaToLongDefault("page", 1));
    const size: usize = @intCast(try ctx.getParaToLongDefault("size", 0)); // 0 = all
    const pageresult = svc.listOrderItem(order_id, page, size) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    defer svc.freeOrderItems(pageresult.rows);
    try ctx.renderJson(.{ .ok = true, .order_items = pageresult.rows, .meta = .{ .total = pageresult.total, .page = page, .size = size } });
}

pub fn createFollow(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    // ── ai-edit-zone: handler hooks ───────────────────────────────
    const follower_id = try ctx.getParaToLong("follower_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing follower_id" });
        return;
    };
    const followee_id = try ctx.getParaToLong("followee_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing followee_id" });
        return;
    };
    // ── end ai-edit-zone ──────────────────────────────────────────
    const id = svc.createFollow(follower_id, followee_id) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true, .id = id });
}

pub fn updateFollow(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    const follower_id = try ctx.getParaToLong("follower_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing follower_id" });
        return;
    };
    const followee_id = try ctx.getParaToLong("followee_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing followee_id" });
        return;
    };
    svc.updateFollow(id, follower_id, followee_id) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn deleteFollow(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    svc.deleteFollow(id) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn listFollow(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const follower_id = try ctx.getParaToLong("follower_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing follower_id" });
        return;
    };
    const page: usize = @intCast(try ctx.getParaToLongDefault("page", 1));
    const size: usize = @intCast(try ctx.getParaToLongDefault("size", 0)); // 0 = all
    const pageresult = svc.listFollow(follower_id, page, size) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    defer svc.freeFollows(pageresult.rows);
    try ctx.renderJson(.{ .ok = true, .follows = pageresult.rows, .meta = .{ .total = pageresult.total, .page = page, .size = size } });
}

pub fn createLike(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    // ── ai-edit-zone: handler hooks ───────────────────────────────
    const user_id = try ctx.getParaToLong("user_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing user_id" });
        return;
    };
    const post_id = try ctx.getParaToLong("post_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing post_id" });
        return;
    };
    // ── end ai-edit-zone ──────────────────────────────────────────
    const id = svc.createLike(user_id, post_id) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true, .id = id });
}

pub fn updateLike(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    const user_id = try ctx.getParaToLong("user_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing user_id" });
        return;
    };
    const post_id = try ctx.getParaToLong("post_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing post_id" });
        return;
    };
    svc.updateLike(id, user_id, post_id) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn deleteLike(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    svc.deleteLike(id) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn listLike(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const post_id = try ctx.getParaToLong("post_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing post_id" });
        return;
    };
    const page: usize = @intCast(try ctx.getParaToLongDefault("page", 1));
    const size: usize = @intCast(try ctx.getParaToLongDefault("size", 0)); // 0 = all
    const pageresult = svc.listLike(post_id, page, size) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    defer svc.freeLikes(pageresult.rows);
    try ctx.renderJson(.{ .ok = true, .likes = pageresult.rows, .meta = .{ .total = pageresult.total, .page = page, .size = size } });
}

pub fn createPost(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    // ── ai-edit-zone: handler hooks ───────────────────────────────
    const author_id = try ctx.getParaToLong("author_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing author_id" });
        return;
    };
    const body = try ctx.getPara("body") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing body" });
        return;
    };
    // ── end ai-edit-zone ──────────────────────────────────────────
    const id = svc.createPost(author_id, body) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true, .id = id });
}

pub fn updatePost(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    const author_id = try ctx.getParaToLong("author_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing author_id" });
        return;
    };
    const body = try ctx.getPara("body") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing body" });
        return;
    };
    svc.updatePost(id, author_id, body) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn deletePost(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    svc.deletePost(id) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn listPost(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const author_id = try ctx.getParaToLong("author_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing author_id" });
        return;
    };
    const page: usize = @intCast(try ctx.getParaToLongDefault("page", 1));
    const size: usize = @intCast(try ctx.getParaToLongDefault("size", 0)); // 0 = all
    const pageresult = svc.listPost(author_id, page, size) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    defer svc.freePosts(pageresult.rows);
    try ctx.renderJson(.{ .ok = true, .posts = pageresult.rows, .meta = .{ .total = pageresult.total, .page = page, .size = size } });
}

pub fn createComment(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    // ── ai-edit-zone: handler hooks ───────────────────────────────
    const post_id = try ctx.getParaToLong("post_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing post_id" });
        return;
    };
    const author_id = try ctx.getParaToLong("author_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing author_id" });
        return;
    };
    const body = try ctx.getPara("body") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing body" });
        return;
    };
    // ── end ai-edit-zone ──────────────────────────────────────────
    const id = svc.createComment(post_id, author_id, body) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true, .id = id });
}

pub fn updateComment(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    const post_id = try ctx.getParaToLong("post_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing post_id" });
        return;
    };
    const author_id = try ctx.getParaToLong("author_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing author_id" });
        return;
    };
    const body = try ctx.getPara("body") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing body" });
        return;
    };
    svc.updateComment(id, post_id, author_id, body) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn deleteComment(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const id = try ctx.getParaToLong("id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing id" });
        return;
    };
    svc.deleteComment(id) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true });
}

pub fn listComment(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const post_id = try ctx.getParaToLong("post_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing post_id" });
        return;
    };
    const page: usize = @intCast(try ctx.getParaToLongDefault("page", 1));
    const size: usize = @intCast(try ctx.getParaToLongDefault("size", 0)); // 0 = all
    const pageresult = svc.listComment(post_id, page, size) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    defer svc.freeComments(pageresult.rows);
    try ctx.renderJson(.{ .ok = true, .comments = pageresult.rows, .meta = .{ .total = pageresult.total, .page = page, .size = size } });
}


// ── ai-edit-zone: extra handlers ─────────────────────────
/// POST /api/v1/orders/checkout?user_id= — transactional cart→order.
pub fn checkout(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const user_id = try ctx.getParaToLong("user_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing user_id" });
        return;
    };
    const id = svc.checkout(user_id) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true, .order_id = id });
}

/// GET /api/v1/feed?user_id=&limit= — followees' posts (QueryEdge batch load).
pub fn feed(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const user_id = try ctx.getParaToLong("user_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing user_id" });
        return;
    };
    const limit: usize = @intCast(try ctx.getParaToLongDefault("limit", 20));
    const rows = svc.feed(user_id, limit) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    defer svc.freeFeed(rows);
    try ctx.renderJson(.{ .ok = true, .feed = rows });
}

/// GET /api/v1/recommend?user_id=&limit= — friend-of-friend suggestions.
pub fn recommend(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const user_id = try ctx.getParaToLong("user_id") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing user_id" });
        return;
    };
    const limit: usize = @intCast(try ctx.getParaToLongDefault("limit", 10));
    const rows = svc.recommend(user_id, limit) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    defer svc.freeRecommend(rows);
    try ctx.renderJson(.{ .ok = true, .users = rows });
}

/// GET /api/v1/orders/mine — own orders only (data_scope row security).
/// Auth: `Authorization: Bearer <JWT>` (see /api/v1/auth/login). The user_id
/// comes from the verified token, NOT from a query param — the row-level scope
/// then filters to that user's orders.
pub fn listMyOrders(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const user_id = try bearerUserId(ctx) orelse {
        ctx.res_status = .unauthorized;
        try ctx.renderJson(.{ .ok = false, .error_msg = "Unauthorized" });
        return;
    };
    const rows = svc.listMyOrders(user_id) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    defer svc.freeScopedOrders(rows);
    try ctx.renderJson(.{ .ok = true, .orders = rows });
}

// ── JWT auth (zfinal.auth.Jwt HS256) — production: secret from env/config.
const jwt_secret = "zent-shop-dev-secret-0123456789abcdef"; // ≥32 bytes

fn authToken(user_id: i64) ![]const u8 {
    const now: i64 = unixSeconds();
    const sub = try std.fmt.allocPrint(std.heap.page_allocator, "{d}", .{user_id});
    defer std.heap.page_allocator.free(sub);
    return zfinal.Jwt.sign(std.heap.page_allocator, jwt_secret, .{
        .sub = sub,
        .exp = now + 3600,
    });
}

fn unixSeconds() i64 {
    var ts: std.c.timespec = undefined;
    _ = std.c.clock_gettime(std.c.CLOCK.REALTIME, &ts);
    return ts.sec;
}

/// User id from a verified `Authorization: Bearer <token>`, or null.
fn bearerUserId(ctx: *zfinal.Context) !?i64 {
    const auth = ctx.getHeader("Authorization") orelse return null;
    if (!std.mem.startsWith(u8, auth, "Bearer ")) return null;
    const token = auth["Bearer ".len..];
    const claims = zfinal.Jwt.verify(std.heap.page_allocator, jwt_secret, token, unixSeconds()) catch return null;
    defer zfinal.Jwt.freeClaims(std.heap.page_allocator, claims);
    return std.fmt.parseInt(i64, claims.sub, 10) catch null;
}

/// POST /api/v1/auth/login?handle= → JWT token (demo auth; sub = user_id).
pub fn login(ctx: *zfinal.Context) !void {
    const svc = try svcOrErr(ctx);
    const handle = try ctx.getPara("handle") orelse {
        try ctx.renderJson(.{ .ok = false, .error_msg = "Missing handle" });
        return;
    };
    const user_id = svc.loginByHandle(handle) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    const token = authToken(user_id) catch |err| {
        try ctx.renderJson(.{ .ok = false, .error_msg = @errorName(err) });
        return;
    };
    try ctx.renderJson(.{ .ok = true, .token = token, .user_id = user_id });
}
// ── end ai-edit-zone ─────────────────────────────────────
