// @generated by `zf crud:zent` — AI: edit inside ai-edit-zone only.
// Regenerate: zf crud:zent <schema.zent|schema.json> [--force]
//! Domain schema (zent Schema-as-code). Primary data layer = zfinal.zent.

const zent = @import("zfinal").zent;
const field = zent.core.field;
const Schema = zent.core.schema.Schema;

pub const User = Schema("User", .{
    .fields = &.{
        field.String("name").NotEmpty(),
        field.String("handle").Unique(),
        field.String("email").Unique().Email(),
    },
    .indexes = &.{
        zent.core.index.Fields(&.{"handle"}),
    },
});

pub const Product = Schema("Product", .{
    .fields = &.{
        field.String("name").NotEmpty(),
        field.Int("price_cents").Positive(),
        field.Int("stock").Default("0").Positive(),
    },
    .edges = &.{
        zent.core.edge.From("seller", User).Field("seller_id"),
    },
});

pub const CartItem = Schema("CartItem", .{
    .fields = &.{
        field.Int("qty").Default("1").Positive(),
    },
    .edges = &.{
        zent.core.edge.From("user", User).Field("user_id"),
        zent.core.edge.From("product", Product).Field("product_id"),
    },
});

pub const Order = Schema("Order", .{
    .fields = &.{
        field.String("status").Default("pending"),
        field.Int("total_cents").Default("0").Positive(),
    },
    .edges = &.{
        zent.core.edge.From("buyer", User).Field("buyer_id"),
    },
    .policy = zent.data_scope.Policy,
});

pub const OrderItem = Schema("OrderItem", .{
    .fields = &.{
        field.Int("qty").Positive(),
        field.Int("price_cents").Positive(),
    },
    .edges = &.{
        zent.core.edge.From("order", Order).Field("order_id"),
        zent.core.edge.From("product", Product).Field("product_id"),
    },
});

pub const Follow = Schema("Follow", .{
    .fields = &.{
    },
    .edges = &.{
        zent.core.edge.From("follower", User).Field("follower_id"),
        zent.core.edge.From("followee", User).Field("followee_id"),
    },
});

pub const Like = Schema("Like", .{
    .fields = &.{
    },
    .edges = &.{
        zent.core.edge.From("user", User).Field("user_id"),
        zent.core.edge.From("post", Post).Field("post_id"),
    },
});

pub const Post = Schema("Post", .{
    .fields = &.{
        field.Text("body").NotEmpty(),
    },
    .edges = &.{
        zent.core.edge.From("author", User).Field("author_id"),
    },
});

pub const Comment = Schema("Comment", .{
    .fields = &.{
        field.Text("body").NotEmpty(),
    },
    .edges = &.{
        zent.core.edge.From("post", Post).Field("post_id"),
        zent.core.edge.From("author", User).Field("author_id"),
    },
});

// ── ai-edit-zone: model hooks ─────────────────────────────────────
// Add edges, privacy rules, or extra Schema decls here.
// ── end ai-edit-zone ──────────────────────────────────────────────
