// @generated by `zf crud:zent` — AI: edit inside ai-edit-zone only.
//! Persistence over zent Client — SQL stays inside zent builders.
const std = @import("std");
const zent = @import("zfinal").zent;
const model = @import("model.zig");

const graph = zent.codegen.graph.buildGraph(&.{ model.User, model.Product, model.CartItem, model.Order, model.OrderItem, model.Follow, model.Like, model.Post, model.Comment });
pub const infos = graph.types;
pub const Client = zent.codegen.client.Client(infos);
const UserInfo = infos[0];
const ProductInfo = infos[1];
const CartItemInfo = infos[2];
const OrderInfo = infos[3];
const OrderItemInfo = infos[4];
const FollowInfo = infos[5];
const LikeInfo = infos[6];
const PostInfo = infos[7];
const CommentInfo = infos[8];

pub const ShopStore = struct {
    allocator: std.mem.Allocator,
    client: Client,

    pub fn init(allocator: std.mem.Allocator, driver: zent.sql_driver.Driver) @This() {
        const client = zent.codegen.client.makeClient(infos, allocator, driver);
        // ── ai-edit-zone: hook wiring ─────────────────────────────
        // Lifecycle hooks (zent.runtime.hook): define callbacks in the
        // custom queries zone, then attach. Needs `var client`:
        //   var client = zent.codegen.client.makeClient(infos, allocator, driver);
        //   client.order = client.order.withHooks(&.{.{ .op = .create, .before = orderBeforeCreate }});
        // ── end ai-edit-zone ──────────────────────────────────────
        return .{
            .allocator = allocator,
            .client = client,
        };
    }
    pub fn createUser(self: *@This(), name: []const u8, handle: []const u8, email: []const u8) !i64 {
        var b = try self.client.user.Create();
        defer b.deinit();
        _ = try b.setFieldValue("name", name);
        _ = try b.setFieldValue("handle", handle);
        _ = try b.setFieldValue("email", email);
        var row = try b.Save();
        defer zent.codegen.deinitEntity(infos, UserInfo, &row, self.allocator);
        return row.id;
    }

    /// Update a User row by id (sets every declared field).
    pub fn updateUser(self: *@This(), id: i64, name: []const u8, handle: []const u8, email: []const u8) !void {
        var ub = self.client.user.Update();
        defer ub.deinit();
        _ = try ub.setFieldValue("name", name);
        _ = try ub.setFieldValue("handle", handle);
        _ = try ub.setFieldValue("email", email);
        _ = try ub.Where(.{self.client.user.predicates.idEQ(.{ .int = id })});
        _ = try ub.Save();
    }

    /// Delete a User row by id.
    pub fn deleteUser(self: *@This(), id: i64) !void {
        var db = self.client.user.Delete();
        defer db.deinit();
        _ = try db.Where(.{self.client.user.predicates.idEQ(.{ .int = id })});
        _ = try db.Exec();
    }

    /// Returns the id of the row whose `handle` equals `value`, or null.
    pub fn findByUniqueHandle(self: *@This(), handle: []const u8) !?i64 {
        var q = self.client.user.Query();
        defer q.deinit();
        const preds = self.client.user.predicates;
        _ = try q.Where(.{preds.handleEQ(.{ .string = handle })});
        var found = try q.All();
        defer {
            for (found.items) |*p| {
                zent.codegen.deinitEntity(infos, UserInfo, p, self.allocator);
            }
            found.deinit();
        }
        if (found.items.len == 0) return null;
        return found.items[0].id;
    }

    /// Returns the id of the row whose `email` equals `value`, or null.
    pub fn findByUniqueEmail(self: *@This(), email: []const u8) !?i64 {
        var q = self.client.user.Query();
        defer q.deinit();
        const preds = self.client.user.predicates;
        _ = try q.Where(.{preds.emailEQ(.{ .string = email })});
        var found = try q.All();
        defer {
            for (found.items) |*p| {
                zent.codegen.deinitEntity(infos, UserInfo, p, self.allocator);
            }
            found.deinit();
        }
        if (found.items.len == 0) return null;
        return found.items[0].id;
    }

    pub fn createProduct(self: *@This(), seller_id: i64, name: []const u8, price_cents: i64, stock: i64) !i64 {
        var b = try self.client.product.Create();
        defer b.deinit();
        _ = try b.setFieldValue("seller_id", seller_id);
        _ = try b.setFieldValue("name", name);
        _ = try b.setFieldValue("price_cents", price_cents);
        _ = try b.setFieldValue("stock", stock);
        var row = try b.Save();
        defer zent.codegen.deinitEntity(infos, ProductInfo, &row, self.allocator);
        return row.id;
    }

    /// Update a Product row by id (sets every declared field).
    pub fn updateProduct(self: *@This(), id: i64, seller_id: i64, name: []const u8, price_cents: i64, stock: i64) !void {
        var ub = self.client.product.Update();
        defer ub.deinit();
        _ = try ub.setFieldValue("seller_id", seller_id);
        _ = try ub.setFieldValue("name", name);
        _ = try ub.setFieldValue("price_cents", price_cents);
        _ = try ub.setFieldValue("stock", stock);
        _ = try ub.Where(.{self.client.product.predicates.idEQ(.{ .int = id })});
        _ = try ub.Save();
    }

    /// Delete a Product row by id.
    pub fn deleteProduct(self: *@This(), id: i64) !void {
        var db = self.client.product.Delete();
        defer db.deinit();
        _ = try db.Where(.{self.client.product.predicates.idEQ(.{ .int = id })});
        _ = try db.Exec();
    }

    pub const ProductRow = struct {
        id: i64,
        seller_id: i64,
        name: []const u8,
        price_cents: i64,
        stock: i64,
    };

    pub const ProductPage = struct { rows: []ProductRow, total: i64 };

    pub fn listProductBySellerId(self: *@This(), seller_id: i64, page: usize, size: usize) !ProductPage {
        var q = self.client.product.Query();
        defer q.deinit();
        const preds = self.client.product.predicates;
        _ = try q.Where(.{preds.seller_idEQ(.{ .int = seller_id })});
        _ = try q.OrderBy(&.{.{ .column = .{ .name = "id", .desc = true } }});
        if (size > 0) {
            var p = try q.paged(page, size);
            defer p.deinit();
            var out = try self.allocator.alloc(ProductRow, p.items.items.len);
            errdefer self.allocator.free(out);
            for (p.items.items, 0..) |e, i| {
                out[i] = .{
                    .id = e.id,
                    .seller_id = e.seller_id orelse 0,
                    .name = try self.allocator.dupe(u8, e.name),
                    .price_cents = e.price_cents,
                    .stock = e.stock,
                };
            }
            return .{ .rows = out, .total = p.total };
        }
        const total = try q.Count();
        var found = try q.All();
        defer {
            for (found.items) |*p| {
                zent.codegen.deinitEntity(infos, ProductInfo, p, self.allocator);
            }
            found.deinit();
        }
        var out = try self.allocator.alloc(ProductRow, found.items.len);
        errdefer self.allocator.free(out);
        for (found.items, 0..) |p, i| {
            out[i] = .{
                .id = p.id,
                .seller_id = p.seller_id orelse 0,
                .name = try self.allocator.dupe(u8, p.name),
                .price_cents = p.price_cents,
                .stock = p.stock,
            };
        }
        return .{ .rows = out, .total = total };
    }

    pub fn freeProducts(self: *@This(), rows: []ProductRow) void {
        for (rows) |r| {
            self.allocator.free(r.name);
        }
        self.allocator.free(rows);
    }

    pub fn createCartItem(self: *@This(), user_id: i64, product_id: i64, qty: i64) !i64 {
        var b = try self.client.cart_item.Create();
        defer b.deinit();
        _ = try b.setFieldValue("user_id", user_id);
        _ = try b.setFieldValue("product_id", product_id);
        _ = try b.setFieldValue("qty", qty);
        var row = try b.Save();
        defer zent.codegen.deinitEntity(infos, CartItemInfo, &row, self.allocator);
        return row.id;
    }

    /// Update a CartItem row by id (sets every declared field).
    pub fn updateCartItem(self: *@This(), id: i64, user_id: i64, product_id: i64, qty: i64) !void {
        var ub = self.client.cart_item.Update();
        defer ub.deinit();
        _ = try ub.setFieldValue("user_id", user_id);
        _ = try ub.setFieldValue("product_id", product_id);
        _ = try ub.setFieldValue("qty", qty);
        _ = try ub.Where(.{self.client.cart_item.predicates.idEQ(.{ .int = id })});
        _ = try ub.Save();
    }

    /// Delete a CartItem row by id.
    pub fn deleteCartItem(self: *@This(), id: i64) !void {
        var db = self.client.cart_item.Delete();
        defer db.deinit();
        _ = try db.Where(.{self.client.cart_item.predicates.idEQ(.{ .int = id })});
        _ = try db.Exec();
    }

    pub const CartItemRow = struct {
        id: i64,
        user_id: i64,
        product_id: i64,
        qty: i64,
    };

    pub const CartItemPage = struct { rows: []CartItemRow, total: i64 };

    pub fn listCartItemByUserId(self: *@This(), user_id: i64, page: usize, size: usize) !CartItemPage {
        var q = self.client.cart_item.Query();
        defer q.deinit();
        const preds = self.client.cart_item.predicates;
        _ = try q.Where(.{preds.user_idEQ(.{ .int = user_id })});
        _ = try q.OrderBy(&.{.{ .column = .{ .name = "id", .desc = true } }});
        if (size > 0) {
            var p = try q.paged(page, size);
            defer p.deinit();
            var out = try self.allocator.alloc(CartItemRow, p.items.items.len);
            errdefer self.allocator.free(out);
            for (p.items.items, 0..) |e, i| {
                out[i] = .{
                    .id = e.id,
                    .user_id = e.user_id orelse 0,
                    .product_id = e.product_id orelse 0,
                    .qty = e.qty,
                };
            }
            return .{ .rows = out, .total = p.total };
        }
        const total = try q.Count();
        var found = try q.All();
        defer {
            for (found.items) |*p| {
                zent.codegen.deinitEntity(infos, CartItemInfo, p, self.allocator);
            }
            found.deinit();
        }
        var out = try self.allocator.alloc(CartItemRow, found.items.len);
        errdefer self.allocator.free(out);
        for (found.items, 0..) |p, i| {
            out[i] = .{
                .id = p.id,
                .user_id = p.user_id orelse 0,
                .product_id = p.product_id orelse 0,
                .qty = p.qty,
            };
        }
        return .{ .rows = out, .total = total };
    }

    pub fn freeCartItems(self: *@This(), rows: []CartItemRow) void {
        self.allocator.free(rows);
    }

    pub fn createOrder(self: *@This(), buyer_id: i64, status: []const u8, total_cents: i64) !i64 {
        var b = try self.client.order.withContext(.{}).Create();
        defer b.deinit();
        _ = try b.setFieldValue("buyer_id", buyer_id);
        _ = try b.setFieldValue("status", status);
        _ = try b.setFieldValue("total_cents", total_cents);
        var row = try b.Save();
        defer zent.codegen.deinitEntity(infos, OrderInfo, &row, self.allocator);
        return row.id;
    }

    /// Update a Order row by id (sets every declared field).
    pub fn updateOrder(self: *@This(), id: i64, buyer_id: i64, status: []const u8, total_cents: i64) !void {
        var ub = self.client.order.withContext(.{}).Update();
        defer ub.deinit();
        _ = try ub.setFieldValue("buyer_id", buyer_id);
        _ = try ub.setFieldValue("status", status);
        _ = try ub.setFieldValue("total_cents", total_cents);
        _ = try ub.Where(.{self.client.order.predicates.idEQ(.{ .int = id })});
        _ = try ub.Save();
    }

    /// Delete a Order row by id.
    pub fn deleteOrder(self: *@This(), id: i64) !void {
        var db = self.client.order.withContext(.{}).Delete();
        defer db.deinit();
        _ = try db.Where(.{self.client.order.predicates.idEQ(.{ .int = id })});
        _ = try db.Exec();
    }

    pub fn createOrderItem(self: *@This(), order_id: i64, product_id: i64, qty: i64, price_cents: i64) !i64 {
        var b = try self.client.order_item.Create();
        defer b.deinit();
        _ = try b.setFieldValue("order_id", order_id);
        _ = try b.setFieldValue("product_id", product_id);
        _ = try b.setFieldValue("qty", qty);
        _ = try b.setFieldValue("price_cents", price_cents);
        var row = try b.Save();
        defer zent.codegen.deinitEntity(infos, OrderItemInfo, &row, self.allocator);
        return row.id;
    }

    /// Update a OrderItem row by id (sets every declared field).
    pub fn updateOrderItem(self: *@This(), id: i64, order_id: i64, product_id: i64, qty: i64, price_cents: i64) !void {
        var ub = self.client.order_item.Update();
        defer ub.deinit();
        _ = try ub.setFieldValue("order_id", order_id);
        _ = try ub.setFieldValue("product_id", product_id);
        _ = try ub.setFieldValue("qty", qty);
        _ = try ub.setFieldValue("price_cents", price_cents);
        _ = try ub.Where(.{self.client.order_item.predicates.idEQ(.{ .int = id })});
        _ = try ub.Save();
    }

    /// Delete a OrderItem row by id.
    pub fn deleteOrderItem(self: *@This(), id: i64) !void {
        var db = self.client.order_item.Delete();
        defer db.deinit();
        _ = try db.Where(.{self.client.order_item.predicates.idEQ(.{ .int = id })});
        _ = try db.Exec();
    }

    pub const OrderItemRow = struct {
        id: i64,
        order_id: i64,
        product_id: i64,
        qty: i64,
        price_cents: i64,
    };

    pub const OrderItemPage = struct { rows: []OrderItemRow, total: i64 };

    pub fn listOrderItemByOrderId(self: *@This(), order_id: i64, page: usize, size: usize) !OrderItemPage {
        var q = self.client.order_item.Query();
        defer q.deinit();
        const preds = self.client.order_item.predicates;
        _ = try q.Where(.{preds.order_idEQ(.{ .int = order_id })});
        _ = try q.OrderBy(&.{.{ .column = .{ .name = "id", .desc = true } }});
        if (size > 0) {
            var p = try q.paged(page, size);
            defer p.deinit();
            var out = try self.allocator.alloc(OrderItemRow, p.items.items.len);
            errdefer self.allocator.free(out);
            for (p.items.items, 0..) |e, i| {
                out[i] = .{
                    .id = e.id,
                    .order_id = e.order_id orelse 0,
                    .product_id = e.product_id orelse 0,
                    .qty = e.qty,
                    .price_cents = e.price_cents,
                };
            }
            return .{ .rows = out, .total = p.total };
        }
        const total = try q.Count();
        var found = try q.All();
        defer {
            for (found.items) |*p| {
                zent.codegen.deinitEntity(infos, OrderItemInfo, p, self.allocator);
            }
            found.deinit();
        }
        var out = try self.allocator.alloc(OrderItemRow, found.items.len);
        errdefer self.allocator.free(out);
        for (found.items, 0..) |p, i| {
            out[i] = .{
                .id = p.id,
                .order_id = p.order_id orelse 0,
                .product_id = p.product_id orelse 0,
                .qty = p.qty,
                .price_cents = p.price_cents,
            };
        }
        return .{ .rows = out, .total = total };
    }

    pub fn freeOrderItems(self: *@This(), rows: []OrderItemRow) void {
        self.allocator.free(rows);
    }

    pub fn createFollow(self: *@This(), follower_id: i64, followee_id: i64) !i64 {
        var b = try self.client.follow.Create();
        defer b.deinit();
        _ = try b.setFieldValue("follower_id", follower_id);
        _ = try b.setFieldValue("followee_id", followee_id);
        var row = try b.Save();
        defer zent.codegen.deinitEntity(infos, FollowInfo, &row, self.allocator);
        return row.id;
    }

    /// Update a Follow row by id (sets every declared field).
    pub fn updateFollow(self: *@This(), id: i64, follower_id: i64, followee_id: i64) !void {
        var ub = self.client.follow.Update();
        defer ub.deinit();
        _ = try ub.setFieldValue("follower_id", follower_id);
        _ = try ub.setFieldValue("followee_id", followee_id);
        _ = try ub.Where(.{self.client.follow.predicates.idEQ(.{ .int = id })});
        _ = try ub.Save();
    }

    /// Delete a Follow row by id.
    pub fn deleteFollow(self: *@This(), id: i64) !void {
        var db = self.client.follow.Delete();
        defer db.deinit();
        _ = try db.Where(.{self.client.follow.predicates.idEQ(.{ .int = id })});
        _ = try db.Exec();
    }

    /// Composite-unique check: does a row with these values already exist?
    pub fn findUniqueFollow(self: *@This(), follower_id: i64, followee_id: i64) !?i64 {
        var q = self.client.follow.Query();
        defer q.deinit();
        const preds = self.client.follow.predicates;
        _ = try q.Where(.{preds.follower_idEQ(.{ .int = follower_id }), preds.followee_idEQ(.{ .int = followee_id })});
        var found = try q.All();
        defer {
            for (found.items) |*e| {
                zent.codegen.deinitEntity(infos, FollowInfo, e, self.allocator);
            }
            found.deinit();
        }
        if (found.items.len == 0) return null;
        return found.items[0].id;
    }

    pub const FollowRow = struct {
        id: i64,
        follower_id: i64,
        followee_id: i64,
    };

    pub const FollowPage = struct { rows: []FollowRow, total: i64 };

    pub fn listFollowByFollowerId(self: *@This(), follower_id: i64, page: usize, size: usize) !FollowPage {
        var q = self.client.follow.Query();
        defer q.deinit();
        const preds = self.client.follow.predicates;
        _ = try q.Where(.{preds.follower_idEQ(.{ .int = follower_id })});
        _ = try q.OrderBy(&.{.{ .column = .{ .name = "id", .desc = true } }});
        if (size > 0) {
            var p = try q.paged(page, size);
            defer p.deinit();
            var out = try self.allocator.alloc(FollowRow, p.items.items.len);
            errdefer self.allocator.free(out);
            for (p.items.items, 0..) |e, i| {
                out[i] = .{
                    .id = e.id,
                    .follower_id = e.follower_id orelse 0,
                    .followee_id = e.followee_id orelse 0,
                };
            }
            return .{ .rows = out, .total = p.total };
        }
        const total = try q.Count();
        var found = try q.All();
        defer {
            for (found.items) |*p| {
                zent.codegen.deinitEntity(infos, FollowInfo, p, self.allocator);
            }
            found.deinit();
        }
        var out = try self.allocator.alloc(FollowRow, found.items.len);
        errdefer self.allocator.free(out);
        for (found.items, 0..) |p, i| {
            out[i] = .{
                .id = p.id,
                .follower_id = p.follower_id orelse 0,
                .followee_id = p.followee_id orelse 0,
            };
        }
        return .{ .rows = out, .total = total };
    }

    pub fn freeFollows(self: *@This(), rows: []FollowRow) void {
        self.allocator.free(rows);
    }

    pub fn createLike(self: *@This(), user_id: i64, post_id: i64) !i64 {
        var b = try self.client.like.Create();
        defer b.deinit();
        _ = try b.setFieldValue("user_id", user_id);
        _ = try b.setFieldValue("post_id", post_id);
        var row = try b.Save();
        defer zent.codegen.deinitEntity(infos, LikeInfo, &row, self.allocator);
        return row.id;
    }

    /// Update a Like row by id (sets every declared field).
    pub fn updateLike(self: *@This(), id: i64, user_id: i64, post_id: i64) !void {
        var ub = self.client.like.Update();
        defer ub.deinit();
        _ = try ub.setFieldValue("user_id", user_id);
        _ = try ub.setFieldValue("post_id", post_id);
        _ = try ub.Where(.{self.client.like.predicates.idEQ(.{ .int = id })});
        _ = try ub.Save();
    }

    /// Delete a Like row by id.
    pub fn deleteLike(self: *@This(), id: i64) !void {
        var db = self.client.like.Delete();
        defer db.deinit();
        _ = try db.Where(.{self.client.like.predicates.idEQ(.{ .int = id })});
        _ = try db.Exec();
    }

    /// Composite-unique check: does a row with these values already exist?
    pub fn findUniqueLike(self: *@This(), user_id: i64, post_id: i64) !?i64 {
        var q = self.client.like.Query();
        defer q.deinit();
        const preds = self.client.like.predicates;
        _ = try q.Where(.{preds.user_idEQ(.{ .int = user_id }), preds.post_idEQ(.{ .int = post_id })});
        var found = try q.All();
        defer {
            for (found.items) |*e| {
                zent.codegen.deinitEntity(infos, LikeInfo, e, self.allocator);
            }
            found.deinit();
        }
        if (found.items.len == 0) return null;
        return found.items[0].id;
    }

    pub const LikeRow = struct {
        id: i64,
        user_id: i64,
        post_id: i64,
    };

    pub const LikePage = struct { rows: []LikeRow, total: i64 };

    pub fn listLikeByPostId(self: *@This(), post_id: i64, page: usize, size: usize) !LikePage {
        var q = self.client.like.Query();
        defer q.deinit();
        const preds = self.client.like.predicates;
        _ = try q.Where(.{preds.post_idEQ(.{ .int = post_id })});
        _ = try q.OrderBy(&.{.{ .column = .{ .name = "id", .desc = true } }});
        if (size > 0) {
            var p = try q.paged(page, size);
            defer p.deinit();
            var out = try self.allocator.alloc(LikeRow, p.items.items.len);
            errdefer self.allocator.free(out);
            for (p.items.items, 0..) |e, i| {
                out[i] = .{
                    .id = e.id,
                    .user_id = e.user_id orelse 0,
                    .post_id = e.post_id orelse 0,
                };
            }
            return .{ .rows = out, .total = p.total };
        }
        const total = try q.Count();
        var found = try q.All();
        defer {
            for (found.items) |*p| {
                zent.codegen.deinitEntity(infos, LikeInfo, p, self.allocator);
            }
            found.deinit();
        }
        var out = try self.allocator.alloc(LikeRow, found.items.len);
        errdefer self.allocator.free(out);
        for (found.items, 0..) |p, i| {
            out[i] = .{
                .id = p.id,
                .user_id = p.user_id orelse 0,
                .post_id = p.post_id orelse 0,
            };
        }
        return .{ .rows = out, .total = total };
    }

    pub fn freeLikes(self: *@This(), rows: []LikeRow) void {
        self.allocator.free(rows);
    }

    pub fn createPost(self: *@This(), author_id: i64, body: []const u8) !i64 {
        var b = try self.client.post.Create();
        defer b.deinit();
        _ = try b.setFieldValue("author_id", author_id);
        _ = try b.setFieldValue("body", body);
        var row = try b.Save();
        defer zent.codegen.deinitEntity(infos, PostInfo, &row, self.allocator);
        return row.id;
    }

    /// Update a Post row by id (sets every declared field).
    pub fn updatePost(self: *@This(), id: i64, author_id: i64, body: []const u8) !void {
        var ub = self.client.post.Update();
        defer ub.deinit();
        _ = try ub.setFieldValue("author_id", author_id);
        _ = try ub.setFieldValue("body", body);
        _ = try ub.Where(.{self.client.post.predicates.idEQ(.{ .int = id })});
        _ = try ub.Save();
    }

    /// Delete a Post row by id.
    pub fn deletePost(self: *@This(), id: i64) !void {
        var db = self.client.post.Delete();
        defer db.deinit();
        _ = try db.Where(.{self.client.post.predicates.idEQ(.{ .int = id })});
        _ = try db.Exec();
    }

    pub const PostRow = struct {
        id: i64,
        author_id: i64,
        body: []const u8,
    };

    pub const PostPage = struct { rows: []PostRow, total: i64 };

    pub fn listPostByAuthorId(self: *@This(), author_id: i64, page: usize, size: usize) !PostPage {
        var q = self.client.post.Query();
        defer q.deinit();
        const preds = self.client.post.predicates;
        _ = try q.Where(.{preds.author_idEQ(.{ .int = author_id })});
        _ = try q.OrderBy(&.{.{ .column = .{ .name = "id", .desc = true } }});
        if (size > 0) {
            var p = try q.paged(page, size);
            defer p.deinit();
            var out = try self.allocator.alloc(PostRow, p.items.items.len);
            errdefer self.allocator.free(out);
            for (p.items.items, 0..) |e, i| {
                out[i] = .{
                    .id = e.id,
                    .author_id = e.author_id orelse 0,
                    .body = try self.allocator.dupe(u8, e.body),
                };
            }
            return .{ .rows = out, .total = p.total };
        }
        const total = try q.Count();
        var found = try q.All();
        defer {
            for (found.items) |*p| {
                zent.codegen.deinitEntity(infos, PostInfo, p, self.allocator);
            }
            found.deinit();
        }
        var out = try self.allocator.alloc(PostRow, found.items.len);
        errdefer self.allocator.free(out);
        for (found.items, 0..) |p, i| {
            out[i] = .{
                .id = p.id,
                .author_id = p.author_id orelse 0,
                .body = try self.allocator.dupe(u8, p.body),
            };
        }
        return .{ .rows = out, .total = total };
    }

    pub fn freePosts(self: *@This(), rows: []PostRow) void {
        for (rows) |r| {
            self.allocator.free(r.body);
        }
        self.allocator.free(rows);
    }

    pub fn createComment(self: *@This(), post_id: i64, author_id: i64, body: []const u8) !i64 {
        var b = try self.client.comment.Create();
        defer b.deinit();
        _ = try b.setFieldValue("post_id", post_id);
        _ = try b.setFieldValue("author_id", author_id);
        _ = try b.setFieldValue("body", body);
        var row = try b.Save();
        defer zent.codegen.deinitEntity(infos, CommentInfo, &row, self.allocator);
        return row.id;
    }

    /// Update a Comment row by id (sets every declared field).
    pub fn updateComment(self: *@This(), id: i64, post_id: i64, author_id: i64, body: []const u8) !void {
        var ub = self.client.comment.Update();
        defer ub.deinit();
        _ = try ub.setFieldValue("post_id", post_id);
        _ = try ub.setFieldValue("author_id", author_id);
        _ = try ub.setFieldValue("body", body);
        _ = try ub.Where(.{self.client.comment.predicates.idEQ(.{ .int = id })});
        _ = try ub.Save();
    }

    /// Delete a Comment row by id.
    pub fn deleteComment(self: *@This(), id: i64) !void {
        var db = self.client.comment.Delete();
        defer db.deinit();
        _ = try db.Where(.{self.client.comment.predicates.idEQ(.{ .int = id })});
        _ = try db.Exec();
    }

    pub const CommentRow = struct {
        id: i64,
        post_id: i64,
        author_id: i64,
        body: []const u8,
    };

    pub const CommentPage = struct { rows: []CommentRow, total: i64 };

    pub fn listCommentByPostId(self: *@This(), post_id: i64, page: usize, size: usize) !CommentPage {
        var q = self.client.comment.Query();
        defer q.deinit();
        const preds = self.client.comment.predicates;
        _ = try q.Where(.{preds.post_idEQ(.{ .int = post_id })});
        _ = try q.OrderBy(&.{.{ .column = .{ .name = "id", .desc = true } }});
        if (size > 0) {
            var p = try q.paged(page, size);
            defer p.deinit();
            var out = try self.allocator.alloc(CommentRow, p.items.items.len);
            errdefer self.allocator.free(out);
            for (p.items.items, 0..) |e, i| {
                out[i] = .{
                    .id = e.id,
                    .post_id = e.post_id orelse 0,
                    .author_id = e.author_id orelse 0,
                    .body = try self.allocator.dupe(u8, e.body),
                };
            }
            return .{ .rows = out, .total = p.total };
        }
        const total = try q.Count();
        var found = try q.All();
        defer {
            for (found.items) |*p| {
                zent.codegen.deinitEntity(infos, CommentInfo, p, self.allocator);
            }
            found.deinit();
        }
        var out = try self.allocator.alloc(CommentRow, found.items.len);
        errdefer self.allocator.free(out);
        for (found.items, 0..) |p, i| {
            out[i] = .{
                .id = p.id,
                .post_id = p.post_id orelse 0,
                .author_id = p.author_id orelse 0,
                .body = try self.allocator.dupe(u8, p.body),
            };
        }
        return .{ .rows = out, .total = total };
    }

    pub fn freeComments(self: *@This(), rows: []CommentRow) void {
        for (rows) |r| {
            self.allocator.free(r.body);
        }
        self.allocator.free(rows);
    }

    // ── ai-edit-zone: custom queries ───────────────────────────────
    /// Get one product by id (owned name; free with `freeProduct`).
    pub fn getProductById(self: *@This(), product_id: i64) !?ProductRow {
        var q = self.client.product.Query();
        defer q.deinit();
        const preds = self.client.product.predicates;
        _ = try q.Where(.{preds.idEQ(.{ .int = product_id })});
        var found = try q.All();
        defer {
            for (found.items) |*p| {
                zent.codegen.deinitEntity(infos, ProductInfo, p, self.allocator);
            }
            found.deinit();
        }
        if (found.items.len == 0) return null;
        const p = found.items[0];
        return .{
            .id = p.id,
            .seller_id = p.seller_id orelse 0,
            .name = try self.allocator.dupe(u8, p.name),
            .price_cents = p.price_cents,
            .stock = p.stock,
        };
    }

    pub fn freeProduct(self: *@This(), row: ProductRow) void {
        self.allocator.free(row.name);
    }

    /// Composite-unique check: does (follower_id, followee_id) already exist?
    pub fn findFollowPair(self: *@This(), follower_id: i64, followee_id: i64) !?i64 {
        var q = self.client.follow.Query();
        defer q.deinit();
        const preds = self.client.follow.predicates;
        _ = try q.Where(.{
            preds.follower_idEQ(.{ .int = follower_id }),
            preds.followee_idEQ(.{ .int = followee_id }),
        });
        var found = try q.All();
        defer {
            for (found.items) |*f| {
                zent.codegen.deinitEntity(infos, FollowInfo, f, self.allocator);
            }
            found.deinit();
        }
        if (found.items.len == 0) return null;
        return found.items[0].id;
    }

    /// Composite-unique check: has this user already liked the post?
    pub fn findLikePair(self: *@This(), user_id: i64, post_id: i64) !?i64 {
        var q = self.client.like.Query();
        defer q.deinit();
        const preds = self.client.like.predicates;
        _ = try q.Where(.{
            preds.user_idEQ(.{ .int = user_id }),
            preds.post_idEQ(.{ .int = post_id }),
        });
        var found = try q.All();
        defer {
            for (found.items) |*l| {
                zent.codegen.deinitEntity(infos, LikeInfo, l, self.allocator);
            }
            found.deinit();
        }
        if (found.items.len == 0) return null;
        return found.items[0].id;
    }

    /// Transactional checkout (zent TxClient): cart → Order + OrderItems,
    /// stock decremented in the same transaction, cart cleared on commit.
    /// Returns the new order id. Errors roll back everything.
    pub fn checkout(self: *@This(), user_id: i64) !i64 {
        var txc = try zent.codegen.client.beginTx(infos, self.client);
        defer txc.deinit();
        errdefer txc.rollback() catch {};

        // 1. read the cart inside the tx
        var q = txc.client.cart_item.Query();
        defer q.deinit();
        const cpreds = txc.client.cart_item.predicates;
        _ = try q.Where(.{cpreds.user_idEQ(.{ .int = user_id })});
        var cart = try q.All();
        defer {
            for (cart.items) |*c| {
                zent.codegen.deinitEntity(infos, CartItemInfo, c, self.allocator);
            }
            cart.deinit();
        }
        if (cart.items.len == 0) return error.EmptyCart;

        // 2. verify stock + compute total (snapshot pricing)
        var total_cents: i64 = 0;
        for (cart.items) |c| {
            const p = try self.getProductById(c.product_id orelse 0) orelse return error.ProductNotFound;
            defer self.freeProduct(p);
            if (p.stock < c.qty) return error.InsufficientStock;
            total_cents += p.price_cents * c.qty;
        }

        // 3. create the order (data_scope entity: attach a context; production
        //    would carry the buyer's request scope, empty ctx = allow-all)
        var ob = try txc.client.order.withContext(.{}).Create();
        defer ob.deinit();
        _ = try ob.setFieldValue("buyer_id", user_id);
        _ = try ob.setFieldValue("status", "pending");
        _ = try ob.setFieldValue("total_cents", total_cents);
        var order_ent = try ob.Save();
        defer zent.codegen.deinitEntity(infos, OrderInfo, &order_ent, self.allocator);
        const order_id = order_ent.id;

        // 4. per item: decrement stock + snapshot OrderItem
        for (cart.items) |c| {
            const p = try self.getProductById(c.product_id orelse 0) orelse return error.ProductNotFound;
            defer self.freeProduct(p);

            var ub = txc.client.product.Update();
            defer ub.deinit();
            _ = try ub.Where(.{txc.client.product.predicates.idEQ(.{ .int = c.product_id orelse 0 })});
            _ = try ub.setExprArgs("stock", "stock - ?", &.{.{ .int = c.qty }});
            _ = try ub.Save();

            var iob = try txc.client.order_item.Create();
            defer iob.deinit();
            _ = try iob.setFieldValue("order_id", order_id);
            _ = try iob.setFieldValue("product_id", c.product_id orelse 0);
            _ = try iob.setFieldValue("qty", c.qty);
            _ = try iob.setFieldValue("price_cents", p.price_cents);
            var oi_ent = try iob.Save();
            defer zent.codegen.deinitEntity(infos, OrderItemInfo, &oi_ent, self.allocator);
            _ = oi_ent.id;
        }

        // 5. clear the cart (same tx)
        var db = try txc.client.cart_item.BulkDelete();
        defer db.deinit();
        _ = try db.Where(.{txc.client.cart_item.predicates.user_idEQ(.{ .int = user_id })});
        _ = try db.Exec();

        try txc.commit();
        return order_id;
    }

    pub const FeedItem = struct {
        post_id: i64,
        author_id: i64,
        author_handle: []const u8,
        body: []const u8,
    };

    /// Followees' posts (newest first) with author handle.
    /// Demonstrates zent `QueryEdge`: authors are batch-loaded in ONE query
    /// (no N+1) from the `author` From edge declared in schema.zent.
    /// Caller owns the slice + each handle; free with `freeFeed`.
    pub fn feedFor(self: *@This(), user_id: i64, limit: usize) ![]FeedItem {
        const alloc = self.allocator;

        // 1. followee ids
        var fq = self.client.follow.Query();
        defer fq.deinit();
        const fpreds = self.client.follow.predicates;
        _ = try fq.Where(.{fpreds.follower_idEQ(.{ .int = user_id })});
        var follows = try fq.All();
        defer {
            for (follows.items) |*f| zent.codegen.deinitEntity(infos, FollowInfo, f, alloc);
            follows.deinit();
        }
        if (follows.items.len == 0) return alloc.alloc(FeedItem, 0);

        var followee_ids: [64]i64 = undefined;
        var followee_count: usize = 0;
        for (follows.items) |f| {
            if (followee_count >= followee_ids.len) break;
            followee_ids[followee_count] = f.followee_id orelse 0;
            followee_count += 1;
        }

        // 2. posts by those authors (IN query), newest first
        // NB: zent WhereIn() still uses the 2-arg append in v0.28 (Zig 0.17
        //     incompatible); sql.In() builds the same predicate without it.
        var values_buf: [64]zent.sql.Value = undefined;
        for (followee_ids[0..followee_count], 0..) |id, i| values_buf[i] = .{ .int = id };
        var pq = self.client.post.Query();
        defer pq.deinit();
        _ = try pq.Where(.{zent.sql.In("author_id", values_buf[0..followee_count])});
        _ = try pq.OrderBy(&.{.{ .column = .{ .name = "id", .desc = true } }});
        _ = pq.Limit(limit);
        var posts = try pq.All();
        defer {
            for (posts.items) |*p| zent.codegen.deinitEntity(infos, PostInfo, p, alloc);
            posts.deinit();
        }

        // 3. batch-load authors via QueryEdge (single query)
        var post_ids: [64]i64 = undefined;
        const m = @min(posts.items.len, post_ids.len);
        for (posts.items[0..m], 0..) |p, i| post_ids[i] = p.id;
        var authors = try self.client.post.QueryEdge("author", post_ids[0..m]);
        defer {
            for (authors.items) |*a| zent.codegen.deinitEntity(infos, UserInfo, a, alloc);
            authors.deinit();
        }

        var out = try alloc.alloc(FeedItem, m);
        errdefer alloc.free(out);
        for (posts.items[0..m], 0..) |p, i| {
            var handle: []const u8 = "?";
            for (authors.items) |a| {
                if (a.id == (p.author_id orelse 0)) {
                    handle = a.handle;
                    break;
                }
            }
            out[i] = .{
                .post_id = p.id,
                .author_id = p.author_id orelse 0,
                .author_handle = try alloc.dupe(u8, handle),
                .body = try alloc.dupe(u8, p.body),
            };
        }
        return out;
    }

    pub fn freeFeed(self: *@This(), rows: []FeedItem) void {
        for (rows) |r| {
            self.allocator.free(r.author_handle);
            self.allocator.free(r.body);
        }
        self.allocator.free(rows);
    }

    pub const RecommendRow = struct {
        user_id: i64,
        handle: []const u8,
    };

    /// Friend-of-friend suggestion (2-hop via Follow rows), excluding self and
    /// already-followed users. Demonstrates graph traversal over the social
    /// edge with plain queries + IN batch loading.
    /// Caller owns slice + handles; free with `freeRecommend`.
    pub fn recommendFor(self: *@This(), user_id: i64, limit: usize) ![]RecommendRow {
        const alloc = self.allocator;

        var fq = self.client.follow.Query();
        defer fq.deinit();
        const fpreds = self.client.follow.predicates;
        _ = try fq.Where(.{fpreds.follower_idEQ(.{ .int = user_id })});
        var follows = try fq.All();
        defer {
            for (follows.items) |*f| zent.codegen.deinitEntity(infos, FollowInfo, f, alloc);
            follows.deinit();
        }

        var followee_ids: [64]i64 = undefined;
        var followee_count: usize = 0;
        for (follows.items) |f| {
            if (followee_count >= followee_ids.len) break;
            followee_ids[followee_count] = f.followee_id orelse 0;
            followee_count += 1;
        }

        // 2-hop: users followed by my followees (exclude self + already followed)
        var cand_ids: [64]i64 = undefined;
        var cand_count: usize = 0;
        for (followee_ids[0..followee_count]) |fid| {
            var hq = self.client.follow.Query();
            defer hq.deinit();
            _ = try hq.Where(.{fpreds.follower_idEQ(.{ .int = fid })});
            var hops = try hq.All();
            defer {
                for (hops.items) |*h| zent.codegen.deinitEntity(infos, FollowInfo, h, alloc);
                hops.deinit();
            }
            for (hops.items) |h| {
                const cid = h.followee_id orelse 0;
                if (cid == user_id) continue;
                var already = false;
                for (followee_ids[0..followee_count]) |f2| {
                    if (f2 == cid) already = true;
                }
                if (already) continue;
                var dup = false;
                for (cand_ids[0..cand_count]) |c| {
                    if (c == cid) dup = true;
                }
                if (dup or cand_count >= cand_ids.len) continue;
                cand_ids[cand_count] = cid;
                cand_count += 1;
            }
        }

        // batch-load candidate users (sql.In, see feed note re: WhereIn)
        var user_values: [64]zent.sql.Value = undefined;
        for (cand_ids[0..cand_count], 0..) |cid, i| user_values[i] = .{ .int = cid };
        var uq = self.client.user.Query();
        defer uq.deinit();
        _ = try uq.Where(.{zent.sql.In("id", user_values[0..cand_count])});
        var users = try uq.All();
        defer {
            for (users.items) |*u| zent.codegen.deinitEntity(infos, UserInfo, u, alloc);
            users.deinit();
        }

        const m = @min(cand_count, limit);
        var out = try alloc.alloc(RecommendRow, m);
        errdefer alloc.free(out);
        for (cand_ids[0..m], 0..) |cid, i| {
            var handle: []const u8 = "?";
            for (users.items) |u| {
                if (u.id == cid) {
                    handle = u.handle;
                    break;
                }
            }
            out[i] = .{ .user_id = cid, .handle = try alloc.dupe(u8, handle) };
        }
        return out;
    }

    pub fn freeRecommend(self: *@This(), rows: []RecommendRow) void {
        for (rows) |r| self.allocator.free(r.handle);
        self.allocator.free(rows);
    }

    /// Row-level security demo (zent data_scope): only `user_id`'s own orders
    /// are returned. The scope predicate is injected automatically from the
    /// `policy: data_scope` Schema declaration — no hand-written WHERE.
    /// Caller owns slice + status strings; free with `freeScopedOrders`.
    pub const ScopedOrderRow = struct {
        id: i64,
        buyer_id: i64,
        status: []const u8,
        total_cents: i64,
    };

    pub fn listOrdersScoped(self: *@This(), user_id: i64) ![]ScopedOrderRow {
        var scope = zent.data_scope.DataScopeFilter.init("dept_id", "buyer_id", .self_, .{ .user_id = user_id });
        const scoped = self.client.order.withContext(scope.context(.{ .user_id = user_id }));
        var q = scoped.Query();
        defer q.deinit();
        _ = try q.OrderBy(&.{.{ .column = .{ .name = "id", .desc = true } }});
        var found = try q.All();
        defer {
            for (found.items) |*o| zent.codegen.deinitEntity(infos, OrderInfo, o, self.allocator);
            found.deinit();
        }
        var out = try self.allocator.alloc(ScopedOrderRow, found.items.len);
        errdefer self.allocator.free(out);
        for (found.items, 0..) |o, i| {
            out[i] = .{
                .id = o.id,
                .buyer_id = o.buyer_id orelse 0,
                .status = try self.allocator.dupe(u8, o.status),
                .total_cents = o.total_cents,
            };
        }
        return out;
    }

    pub fn freeScopedOrders(self: *@This(), rows: []ScopedOrderRow) void {
        for (rows) |r| self.allocator.free(r.status);
        self.allocator.free(rows);
    }

    /// Lifecycle hook example (zent runtime.hook): runs before every Order
    /// create. To enable: in `init`, switch `const client` → `var client`
    /// and add `client.order = client.order.withHooks(&.{.{ .op = .create,
    /// .before = orderBeforeCreate }});` inside the hook-wiring zone.
    pub fn orderBeforeCreate(ctx: *zent.runtime.hook.HookContext) zent.runtime.hook.HookError!void {
        // example guard: reject negative totals
        for (ctx.mutated orelse &.{}) |v| {
            if (v == .int and v.int < 0) return error.ValidationFailed;
        }
        return;
    }
    // ── end ai-edit-zone ──────────────────────────────────────────

    comptime {        _ = UserInfo;
        _ = OrderInfo;
    }
};
