// @generated by zf routes — DO NOT EDIT
// Regenerate: zf routes
const handler = @import("handler.zig");

pub fn register(app: anytype) !void {
    try app.post("/api/v1/users", handler.createUser);
    try app.put("/api/v1/users", handler.updateUser);
    try app.delete("/api/v1/users", handler.deleteUser);
    try app.post("/api/v1/products", handler.createProduct);
    try app.put("/api/v1/products", handler.updateProduct);
    try app.delete("/api/v1/products", handler.deleteProduct);
    try app.get("/api/v1/products", handler.listProduct);
    try app.post("/api/v1/cart_items", handler.createCartItem);
    try app.put("/api/v1/cart_items", handler.updateCartItem);
    try app.delete("/api/v1/cart_items", handler.deleteCartItem);
    try app.get("/api/v1/cart_items", handler.listCartItem);
    try app.post("/api/v1/orders", handler.createOrder);
    try app.put("/api/v1/orders", handler.updateOrder);
    try app.delete("/api/v1/orders", handler.deleteOrder);
    try app.post("/api/v1/order_items", handler.createOrderItem);
    try app.put("/api/v1/order_items", handler.updateOrderItem);
    try app.delete("/api/v1/order_items", handler.deleteOrderItem);
    try app.get("/api/v1/order_items", handler.listOrderItem);
    try app.post("/api/v1/follows", handler.createFollow);
    try app.put("/api/v1/follows", handler.updateFollow);
    try app.delete("/api/v1/follows", handler.deleteFollow);
    try app.get("/api/v1/follows", handler.listFollow);
    try app.post("/api/v1/likes", handler.createLike);
    try app.put("/api/v1/likes", handler.updateLike);
    try app.delete("/api/v1/likes", handler.deleteLike);
    try app.get("/api/v1/likes", handler.listLike);
    try app.post("/api/v1/posts", handler.createPost);
    try app.put("/api/v1/posts", handler.updatePost);
    try app.delete("/api/v1/posts", handler.deletePost);
    try app.get("/api/v1/posts", handler.listPost);
    try app.post("/api/v1/comments", handler.createComment);
    try app.put("/api/v1/comments", handler.updateComment);
    try app.delete("/api/v1/comments", handler.deleteComment);
    try app.get("/api/v1/comments", handler.listComment);
    try app.post("/api/v1/orders/checkout", handler.checkout);
    try app.get("/api/v1/feed", handler.feed);
    try app.get("/api/v1/recommend", handler.recommend);
    try app.get("/api/v1/orders/mine", handler.listMyOrders);
}
