// @generated by `zf crud:zent` — AI: edit inside ai-edit-zone only.
const std = @import("std");
const persist = @import("persistence.zig");

pub const ShopService = struct {
    store: *persist.ShopStore,

    pub fn init(store: *persist.ShopStore) @This() {
        return .{ .store = store };
    }

    pub fn createUser(self: *@This(), name: []const u8, handle: []const u8, email: []const u8) !i64 {
        // ── ai-edit-zone: business rules ────────────────────────────
        if (name.len == 0) return error.InvalidInput;
        if (handle.len == 0) return error.InvalidInput;
        if (email.len == 0) return error.InvalidInput;
        if (try self.store.findByUniqueHandle(handle) != null) return error.Duplicate;
        if (try self.store.findByUniqueEmail(email) != null) return error.Duplicate;
        // ── end ai-edit-zone ──────────────────────────────────────
        return try self.store.createUser(name, handle, email);
    }

    pub fn updateUser(self: *@This(), id: i64, name: []const u8, handle: []const u8, email: []const u8) !void {
        if (id <= 0) return error.InvalidInput;
        if (name.len == 0) return error.InvalidInput;
        if (handle.len == 0) return error.InvalidInput;
        if (email.len == 0) return error.InvalidInput;
        return self.store.updateUser(id, name, handle, email);
    }

    pub fn deleteUser(self: *@This(), id: i64) !void {
        if (id <= 0) return error.InvalidInput;
        return self.store.deleteUser(id);
    }

    pub fn createProduct(self: *@This(), seller_id: i64, name: []const u8, price_cents: i64, stock: i64) !i64 {
        // ── ai-edit-zone: business rules ────────────────────────────
        if (seller_id <= 0) return error.InvalidInput;
        if (name.len == 0) return error.InvalidInput;
        // ── end ai-edit-zone ──────────────────────────────────────
        return try self.store.createProduct(seller_id, name, price_cents, stock);
    }

    pub fn updateProduct(self: *@This(), id: i64, seller_id: i64, name: []const u8, price_cents: i64, stock: i64) !void {
        if (id <= 0) return error.InvalidInput;
        if (name.len == 0) return error.InvalidInput;
        return self.store.updateProduct(id, seller_id, name, price_cents, stock);
    }

    pub fn deleteProduct(self: *@This(), id: i64) !void {
        if (id <= 0) return error.InvalidInput;
        return self.store.deleteProduct(id);
    }

    pub fn listProduct(self: *@This(), seller_id: i64, page: usize, size: usize) !persist.ShopStore.ProductPage {
        if (seller_id <= 0) return error.InvalidInput;
        return try self.store.listProductBySellerId(seller_id, page, size);
    }

    pub fn freeProducts(self: *@This(), rows: []persist.ShopStore.ProductRow) void {
        self.store.freeProducts(rows);
    }

    pub fn createCartItem(self: *@This(), user_id: i64, product_id: i64, qty: i64) !i64 {
        // ── ai-edit-zone: business rules ────────────────────────────
        if (user_id <= 0) return error.InvalidInput;
        if (product_id <= 0) return error.InvalidInput;
        // ── end ai-edit-zone ──────────────────────────────────────
        return try self.store.createCartItem(user_id, product_id, qty);
    }

    pub fn updateCartItem(self: *@This(), id: i64, user_id: i64, product_id: i64, qty: i64) !void {
        if (id <= 0) return error.InvalidInput;
        return self.store.updateCartItem(id, user_id, product_id, qty);
    }

    pub fn deleteCartItem(self: *@This(), id: i64) !void {
        if (id <= 0) return error.InvalidInput;
        return self.store.deleteCartItem(id);
    }

    pub fn listCartItem(self: *@This(), user_id: i64, page: usize, size: usize) !persist.ShopStore.CartItemPage {
        if (user_id <= 0) return error.InvalidInput;
        return try self.store.listCartItemByUserId(user_id, page, size);
    }

    pub fn freeCartItems(self: *@This(), rows: []persist.ShopStore.CartItemRow) void {
        self.store.freeCartItems(rows);
    }

    pub fn createOrder(self: *@This(), buyer_id: i64, status: []const u8, total_cents: i64) !i64 {
        // ── ai-edit-zone: business rules ────────────────────────────
        if (buyer_id <= 0) return error.InvalidInput;
        if (status.len == 0) return error.InvalidInput;
        // ── end ai-edit-zone ──────────────────────────────────────
        return try self.store.createOrder(buyer_id, status, total_cents);
    }

    pub fn updateOrder(self: *@This(), id: i64, buyer_id: i64, status: []const u8, total_cents: i64) !void {
        if (id <= 0) return error.InvalidInput;
        if (status.len == 0) return error.InvalidInput;
        return self.store.updateOrder(id, buyer_id, status, total_cents);
    }

    pub fn deleteOrder(self: *@This(), id: i64) !void {
        if (id <= 0) return error.InvalidInput;
        return self.store.deleteOrder(id);
    }

    pub fn createOrderItem(self: *@This(), order_id: i64, product_id: i64, qty: i64, price_cents: i64) !i64 {
        // ── ai-edit-zone: business rules ────────────────────────────
        if (order_id <= 0) return error.InvalidInput;
        if (product_id <= 0) return error.InvalidInput;
        // ── end ai-edit-zone ──────────────────────────────────────
        return try self.store.createOrderItem(order_id, product_id, qty, price_cents);
    }

    pub fn updateOrderItem(self: *@This(), id: i64, order_id: i64, product_id: i64, qty: i64, price_cents: i64) !void {
        if (id <= 0) return error.InvalidInput;
        return self.store.updateOrderItem(id, order_id, product_id, qty, price_cents);
    }

    pub fn deleteOrderItem(self: *@This(), id: i64) !void {
        if (id <= 0) return error.InvalidInput;
        return self.store.deleteOrderItem(id);
    }

    pub fn listOrderItem(self: *@This(), order_id: i64, page: usize, size: usize) !persist.ShopStore.OrderItemPage {
        if (order_id <= 0) return error.InvalidInput;
        return try self.store.listOrderItemByOrderId(order_id, page, size);
    }

    pub fn freeOrderItems(self: *@This(), rows: []persist.ShopStore.OrderItemRow) void {
        self.store.freeOrderItems(rows);
    }

    pub fn createFollow(self: *@This(), follower_id: i64, followee_id: i64) !i64 {
        // ── ai-edit-zone: business rules ────────────────────────────
        if (follower_id <= 0) return error.InvalidInput;
        if (followee_id <= 0) return error.InvalidInput;
        if (follower_id == followee_id) return error.InvalidInput;
        if (try self.store.findFollowPair(follower_id, followee_id) != null) return error.Duplicate;
        // ── end ai-edit-zone ──────────────────────────────────────
        return try self.store.createFollow(follower_id, followee_id);
    }

    pub fn updateFollow(self: *@This(), id: i64, follower_id: i64, followee_id: i64) !void {
        if (id <= 0) return error.InvalidInput;
        return self.store.updateFollow(id, follower_id, followee_id);
    }

    pub fn deleteFollow(self: *@This(), id: i64) !void {
        if (id <= 0) return error.InvalidInput;
        return self.store.deleteFollow(id);
    }

    pub fn listFollow(self: *@This(), follower_id: i64, page: usize, size: usize) !persist.ShopStore.FollowPage {
        if (follower_id <= 0) return error.InvalidInput;
        return try self.store.listFollowByFollowerId(follower_id, page, size);
    }

    pub fn freeFollows(self: *@This(), rows: []persist.ShopStore.FollowRow) void {
        self.store.freeFollows(rows);
    }

    pub fn createLike(self: *@This(), user_id: i64, post_id: i64) !i64 {
        // ── ai-edit-zone: business rules ────────────────────────────
        if (user_id <= 0) return error.InvalidInput;
        if (post_id <= 0) return error.InvalidInput;
        if (try self.store.findLikePair(user_id, post_id) != null) return error.Duplicate;
        // ── end ai-edit-zone ──────────────────────────────────────
        return try self.store.createLike(user_id, post_id);
    }

    pub fn updateLike(self: *@This(), id: i64, user_id: i64, post_id: i64) !void {
        if (id <= 0) return error.InvalidInput;
        return self.store.updateLike(id, user_id, post_id);
    }

    pub fn deleteLike(self: *@This(), id: i64) !void {
        if (id <= 0) return error.InvalidInput;
        return self.store.deleteLike(id);
    }

    pub fn listLike(self: *@This(), post_id: i64, page: usize, size: usize) !persist.ShopStore.LikePage {
        if (post_id <= 0) return error.InvalidInput;
        return try self.store.listLikeByPostId(post_id, page, size);
    }

    pub fn freeLikes(self: *@This(), rows: []persist.ShopStore.LikeRow) void {
        self.store.freeLikes(rows);
    }

    pub fn createPost(self: *@This(), author_id: i64, body: []const u8) !i64 {
        // ── ai-edit-zone: business rules ────────────────────────────
        if (author_id <= 0) return error.InvalidInput;
        if (body.len == 0) return error.InvalidInput;
        // ── end ai-edit-zone ──────────────────────────────────────
        return try self.store.createPost(author_id, body);
    }

    pub fn updatePost(self: *@This(), id: i64, author_id: i64, body: []const u8) !void {
        if (id <= 0) return error.InvalidInput;
        if (body.len == 0) return error.InvalidInput;
        return self.store.updatePost(id, author_id, body);
    }

    pub fn deletePost(self: *@This(), id: i64) !void {
        if (id <= 0) return error.InvalidInput;
        return self.store.deletePost(id);
    }

    pub fn listPost(self: *@This(), author_id: i64, page: usize, size: usize) !persist.ShopStore.PostPage {
        if (author_id <= 0) return error.InvalidInput;
        return try self.store.listPostByAuthorId(author_id, page, size);
    }

    pub fn freePosts(self: *@This(), rows: []persist.ShopStore.PostRow) void {
        self.store.freePosts(rows);
    }

    pub fn createComment(self: *@This(), post_id: i64, author_id: i64, body: []const u8) !i64 {
        // ── ai-edit-zone: business rules ────────────────────────────
        if (post_id <= 0) return error.InvalidInput;
        if (author_id <= 0) return error.InvalidInput;
        if (body.len == 0) return error.InvalidInput;
        // ── end ai-edit-zone ──────────────────────────────────────
        return try self.store.createComment(post_id, author_id, body);
    }

    pub fn updateComment(self: *@This(), id: i64, post_id: i64, author_id: i64, body: []const u8) !void {
        if (id <= 0) return error.InvalidInput;
        if (body.len == 0) return error.InvalidInput;
        return self.store.updateComment(id, post_id, author_id, body);
    }

    pub fn deleteComment(self: *@This(), id: i64) !void {
        if (id <= 0) return error.InvalidInput;
        return self.store.deleteComment(id);
    }

    pub fn listComment(self: *@This(), post_id: i64, page: usize, size: usize) !persist.ShopStore.CommentPage {
        if (post_id <= 0) return error.InvalidInput;
        return try self.store.listCommentByPostId(post_id, page, size);
    }

    pub fn freeComments(self: *@This(), rows: []persist.ShopStore.CommentRow) void {
        self.store.freeComments(rows);
    }

    // ── ai-edit-zone: extra service methods ───────────────────────
    /// Transactional checkout: cart → order + stock decrement (see store).
    pub fn checkout(self: *@This(), user_id: i64) !i64 {
        if (user_id <= 0) return error.InvalidInput;
        return try self.store.checkout(user_id);
    }

    /// Followees' posts feed (QueryEdge batch author load).
    pub fn feed(self: *@This(), user_id: i64, limit: usize) ![]persist.ShopStore.FeedItem {
        if (user_id <= 0) return error.InvalidInput;
        return try self.store.feedFor(user_id, limit);
    }

    pub fn freeFeed(self: *@This(), rows: []persist.ShopStore.FeedItem) void {
        self.store.freeFeed(rows);
    }

    /// Friend-of-friend suggestions (2-hop graph).
    pub fn recommend(self: *@This(), user_id: i64, limit: usize) ![]persist.ShopStore.RecommendRow {
        if (user_id <= 0) return error.InvalidInput;
        return try self.store.recommendFor(user_id, limit);
    }

    pub fn freeRecommend(self: *@This(), rows: []persist.ShopStore.RecommendRow) void {
        self.store.freeRecommend(rows);
    }

    /// Own orders only (row-level security via zent data_scope).
    pub fn listMyOrders(self: *@This(), user_id: i64) ![]persist.ShopStore.ScopedOrderRow {
        if (user_id <= 0) return error.InvalidInput;
        return try self.store.listOrdersScoped(user_id);
    }

    pub fn freeScopedOrders(self: *@This(), rows: []persist.ShopStore.ScopedOrderRow) void {
        self.store.freeScopedOrders(rows);
    }

    /// Resolve a user id by unique handle (used by /api/v1/auth/login).
    pub fn loginByHandle(self: *@This(), handle: []const u8) !i64 {
        if (handle.len == 0) return error.InvalidInput;
        return (try self.store.findByUniqueHandle(handle)) orelse error.UserNotFound;
    }
    // ── end ai-edit-zone ──────────────────────────────────────────
};
