// @generated by zf routes — DO NOT EDIT
// Regenerate: zf routes
const handler = @import("handler.zig");

pub fn register(app: anytype) !void {
    try app.get("/users/:user_id/orders", handler.index);
    try app.get("/users/:user_id/orders/:id", handler.show);
    try app.post("/users/:user_id/orders", handler.create);
}
