// @generated by zf routes — DO NOT EDIT
// Regenerate: zf routes
const handler = @import("handler.zig");
const ic = @import("../../interceptors.zig");

pub fn register(app: anytype) !void {
    try app.getWithInterceptors("/users", handler.index, &.{ ic.auth, ic.access_log });
    try app.getWithInterceptors("/users/:id", handler.show, &.{ ic.auth, ic.access_log });
    try app.postWithInterceptors("/users", handler.create, &.{ ic.auth, ic.access_log });
    try app.putWithInterceptors("/users/:id", handler.update, &.{ ic.auth, ic.access_log });
    try app.deleteWithInterceptors("/users/:id", handler.destroy, &.{ ic.auth, ic.access_log });
    try app.postWithInterceptors("/auth/login", handler.login, &.{ ic.auth, ic.access_log });
}
