// @generated by zf routes — DO NOT EDIT
// Regenerate: zf routes
const handler = @import("handler.zig");

pub fn register(app: anytype) !void {
    try app.get("/assets", handler.index);
    try app.get("/assets/*path", handler.get);
}
